import {
  faBars,
  faCheckCircle,
  faComment,
  faCommentAlt,
  faCommentDots,
  faCreditCard,
  faEnvelope,
  faEnvelopeOpen,
  faExclamationCircle,
  faFlag,
  faHome,
  faInfo,
  faInfoCircle,
  faMapMarkedAlt,
  faPhone,
  faQuestionCircle,
  faSignInAlt, faSignOutAlt,
  faStar,
  faStarAndCrescent,
  faStarHalf, faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserCircle,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeIcons = [
  faHome,
  faSignInAlt,
  faTimes,
  faTrashAlt,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
  faBars,
  faFlag,
  faCreditCard,
  faUserCircle,
  faMapMarkedAlt,
  faPhone,
  faEnvelope,
  faEnvelopeOpen,
  faCheckCircle,
  faExclamationCircle,
  faStar,
  faStarAndCrescent,
  faStarHalf,
  faComment,
  faCommentAlt,
  faCommentDots,
  faQuestionCircle,
  faInfo,
  faInfoCircle,
  faThList,
  faSignOutAlt
  // jhipster-needle-add-icon-import
];
